---
AWSTemplateFormatVersion: 2010-09-09
Description: Dynamo stack for ci example
Resources:
  ExampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Example
      AttributeDefinitions:
        - AttributeName: Example
          AttributeType: "N"
        - AttributeName: ExampleStamp
          AttributeType: "S"
      KeySchema:
        - AttributeName: Example
          KeyType: HASH
        - AttributeName: ExampleStamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
