---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates a ci user for github actions
Parameters:
  Username:
    Type: String
    Default: ci-user
  Password:
    Type: String
    Default: Abcd1234/*-.
    NoEcho: true
Resources:
  AppUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Username
      LoginProfile:
        Password: !Ref Password
        PasswordResetRequired: false
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/PowerUserAccess
      Policies:
        - PolicyName: s3Actions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: arn:aws:s3:::post-artifacts
                Action:
                  - s3:*Object
  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AppUser
Outputs:
  UserAccessKey:
    Value: !Ref UserAccessKey
  UserAccessKeySecretKey:
    Value: !GetAtt UserAccessKey.SecretAccessKey
